### PR TITLE
chore: add nvm for managing node + updating readme accordingly

### PR DESCRIPTION
**Pull request by ZiyedB**
Done #1

### CODE REVIEW

**Review by jbargu — CHANGES_REQUESTED** [review]
Great! Please just resolve the conflicts I have caused. Sorry about that!

**Comment by ZiyedB** [comment]
Do you guys use labels on PRs ? Wondering if we can get access to that, something like the status of the PR ( awaiting updates, ready for review, feature, doc ? )

**Comment by jbargu** [comment]
> Do you guys use labels on PRs ? Wondering if we can get access to that, something like the status of the PR ( awaiting updates, ready for review, feature, doc ? )

We usually assign people when waiting for the update and when the PR is ready to review, the author can  remove the [WIP] tag and add a reviewer. However I added the labels for `awaiting updates` and `ready for review` if this is the workflow you prefer.

**Comment by ZiyedB** [comment]
All good @jbargu I think I might just need some permission to add labels ( on issues ) & PRs currently can't do any one of those

**Pull request merged**
